module.exports = [
    { word: "моло*о", correct: "чк", all: [ "чьк" ] },
    { word: "бо*а", correct: "чк", all: [ "чьк" ] },
    { word: "пе*а", correct: "чк", all: [ "чьк" ] },
    { word: "ёло*а", correct: "чк", all: [ "чьк" ] },
    { word: "о*и", correct: "чк", all: [ "чьк" ] },
    { word: "яи*о", correct: "чк", all: [ "чьк" ] },
    { word: "колю*а", correct: "чк", all: [ "чьк" ] },
    { word: "бело*а", correct: "чк", all: [ "чьк" ] },
    { word: "ове*а", correct: "чк", all: [ "чьк" ] },
    { word: "грибо*и", correct: "чк", all: [ "чьк" ] },
    { word: "вазо*а", correct: "чк", all: [ "чьк" ] },
    { word: "спи*а", correct: "чк", all: [ "чьк" ] },
    { word: "па*а", correct: "чк", all: [ "чьк" ] },
    { word: "вну*а", correct: "чк", all: [ "чьк" ] },
    { word: "носо*и", correct: "чк", all: [ "чьк" ] },
    { word: "привы*а", correct: "чк", all: [ "чьк" ] },
    { word: "до*и", correct: "чк", all: [ "чьк" ] },

    { word: "яи*ый", correct: "чн", all: [ "чьн" ] },
    { word: "но*ой", correct: "чн", all: [ "чьн" ] },
    { word: "пе*ой", correct: "чн", all: [ "чьн" ] },
    { word: "ру*ой", correct: "чн", all: [ "чьн" ] },
    { word: "ули*ый", correct: "чн", all: [ "чьн" ] },
    { word: "пе*ик", correct: "чн", all: [ "чьн" ] },
    { word: "ве*ый", correct: "чн", all: [ "чьн" ] },
    { word: "ску*ый", correct: "чн", all: [ "чьн" ] },
    { word: "встре*ый", correct: "чн", all: [ "чьн" ] },
    { word: "но*ой", correct: "чн", all: [ "чьн" ] },
    { word: "да*ый", correct: "чн", all: [ "чьн" ] },
    { word: "четвери*ый", correct: "чн", all: [ "чьн" ] },
]