module.exports = [
    { word: "в~робей", correct: "о", all: [ "а" ] },
    { word: "вор~бей", correct: "о", all: [ "а" ] },
    { word: "л~сица", correct: "и", all: [ "е" ] },
    { word: "вдру~", correct: "г", all: [ "к" ] },
    { word: "М~сква", correct: "о", all: [ "а" ] },
    { word: "яг~да", correct: "о", all: [ "а" ] },
    { word: "к~рандаш", correct: "а", all: [ "о" ] },
    { word: "кар~ндаш", correct: "а", all: [ "о" ] },
    { word: "р~бота", correct: "а", all: [ "о" ] },
    { word: "р~бочий", correct: "а", all: [ "о" ] },
    { word: "с~рока", correct: "о", all: [ "а" ] },
    { word: "п~суда", correct: "о", all: [ "а" ] },
    { word: "т~варищ", correct: "о", all: [ "а" ] },
    { word: "товар~щ", correct: "и", all: [ "е" ] },
    { word: "дев~чка", correct: "о", all: [ "а" ] },
    { word: "к~пуста", correct: "а", all: [ "о" ] },
    { word: "х~роший", correct: "о", all: [ "а" ] },
    { word: "т~традь", correct: "е", all: [ "и" ] },
    { word: "з~вод", correct: "а", all: [ "о" ] },
    { word: "м~шина", correct: "а", all: [ "о" ] },
    { word: "ф~милия", correct: "а", all: [ "о" ] },
    { word: "фамил~я", correct: "и", all: [ "е" ] },
    { word: "п~тух", correct: "е", all: [ "и" ] },
    { word: "уч~ник", correct: "е", all: [ "и" ] },
    { word: "~дежда", correct: "о", all: [ "а" ] },
    { word: "д~журный", correct: "е", all: [ "и" ] },
    { word: "с~бака", correct: "о", all: [ "а" ] },
    { word: "быстр~", correct: "о", all: [ "а" ] },
    { word: "р~бята", correct: "е", all: [ "и" ] },
    { word: "вес~ло", correct: "е", all: [ "и" ] },
    { word: "весел~", correct: "о", all: [ "а" ] },
    { word: "скор~", correct: "о", all: [ "а" ] },
    { word: "п~льто", correct: "а", all: [ "о" ] },
    { word: "за~ц", correct: "я", all: [ "и", "е" ] },
    { word: "м~дведь", correct: "е", all: [ "и" ] },
    { word: "м~дведица", correct: "е", all: [ "и" ] },
    { word: "медвед~ца", correct: "и", all: [ "е" ] },
    { word: "учит~ль", correct: "е", all: [ "и" ] },
    { word: "учит~льница", correct: "е", all: [ "и" ] },
    { word: "учительн~ца", correct: "и", all: [ "е" ] },
    { word: "с~пог", correct: "а", all: [ "о" ] },
    { word: "сапо~", correct: "г", all: [ "к", "кь", "гь" ] },
    { word: "м~роз", correct: "о", all: [ "а" ] },
    { word: "моро~", correct: "з", all: [ "с", "сь", "зь" ] },
    { word: "д~ревня", correct: "е", all: [ "и" ] },
    { word: "к~ньки", correct: "о", all: [ "а" ] },
    { word: "вет~р", correct: "е", all: [ "и" ] },
    { word: "су~ота", correct: "бб", all: [ "б", "п", "пп" ] },
    { word: "кла~", correct: "сс", all: [ "с", "з", "зз" ] },
    { word: "ру~кий язык", correct: "сс", all: [ "с", "з", "зз" ] },
    { word: "русский ~зык", correct: "я", all: [ "е", "и" ] },
    { word: "б~рёза", correct: "е", all: [ "и" ] },
]